blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('tech-blog-admin/', admin.site.urls),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *
from .feeds import LatestPostsFeed

app_name = 'posts'

urlpatterns = [
    path('post/<int:pk>/<slug:slugy>/<int:year>/<int:month>/<int:day>/', PostDetailView.as_view(), name='post-detail'),
    path('categories/<slug:slug>/', PostCategories.as_view(), name='post-by-categories'),
    path('profile/<slug:username>/', ViewPostAuthorProfile.as_view(), name='view-author-profile'),
    path('<str:username>/posts/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/<slug:slug>/update/', PostUpdateView.as_view(), name='update-post'),
    path('post/<int:pk>/<slug:slug>/delete/', PostDeleteView.as_view(), name='delete-post'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post_list_by_tag'),
    path('trending/', TrendingPostsView.as_view(), name='trending-posts'),
    path('feed/', LatestPostsFeed(), name='posts_feed'),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('categories/', PostCategories.as_view(), name='categories'),
    path('search', SearchView.as_view(), name='search'),
    path('', PostListView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    # authentication
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    # path('logout/', UserLogoutView.as_view(), name='logout'),

    # register and activate account
    path('register/', RegistrationView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm-email/<uidb64>/<token>/', ActivateAccountView.as_view(), name='confirm-email'),

    # change password
    path('password-change/', ChangePasswordView.as_view(), name='password-change'),
    path('password-change/done/', ChangePasswordDoneView.as_view(), name='password-change-done'),

    # reset password
    path('password-reset/', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset/done/', ResetPasswordDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset/complete/', ResetPasswordCompleteView.as_view(), name='password-reset-complete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils.text import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django_comments_xtd.models import XtdComment
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=70, unique=True)
    slug = models.SlugField(max_length=70, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('posts:post-by-categories', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.name}'


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    POST_STATUS = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True)
    author = models.ForeignKey(User, related_name='author_post', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='categories', on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=POST_STATUS, default='draft')
    content = HTMLField()
    date_posted = models.DateTimeField(default=now)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ('date_posted',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            count = 1
            if Post.objects.all().filter(slug=self.slug).exists():
                count += 1
                self.slug = slugify(self.title) + '-' + str(count)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk': self.pk, 'slugy': self.slug,
                                                    'year': self.date_posted.year,
                                                    'month': self.date_posted.month,
                                                    'day': self.date_posted.day})

    def __str__(self):
        return f'{self.title}'


class PostComment(XtdComment):
    post_comment = models.ForeignKey(Post, related_name='post_comments', on_delete=models.CASCADE)

posts/views.py
from django.shortcuts import get_object_or_404
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.views.generic import ListView, DetailView, FormView, CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin, LoginRequiredMixin
from taggit.models import Tag
from .models import Post, Category


class PostListView(ListView):
    """List all published posts."""
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 5
    extra_context = {'title': 'Home'}
    context_object_name = 'posts'

    def get_queryset(self):
        if self.kwargs.get('tag_slug'):
            tag = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
            return Post.published.filter(tags__in=[tag]).order_by('-date_posted')
        return Post.published.order_by('-date_posted')


class PostDetailView(DetailView):
    """Detail of a post."""
    model = Post
    template_name = 'posts/post_detail.html'
    # slug_field = 'slugy'
    slug_url_kwarg = 'slugy'

    def get_context_data(self, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'), slug=self.kwargs.get('slugy'),
                                 date_posted__year=self.kwargs.get('year'),
                                 date_posted__month=self.kwargs.get('month'),
                                 date_posted__day=self.kwargs.get('day'))
        context = {'title': post.title, 'post': post}
        return context


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Create a post by authenticated and permitted users."""
    model = Post
    permission_required = 'posts.can_add'
    fields = ['category', 'title', 'content', 'status', 'tags']
    extra_context = {'title': 'Create Post'}
    success_message = 'Post Added!'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Update a post by the author after authentication."""
    model = Post
    permission_denied_message = 'You can\'t edit this post'
    extra_context = {'title': 'Update Post'}
    fields = ['category', 'title', 'content', 'status', 'tags']
    success_message = 'Post Edited Successfully!'
    slug_url_kwarg = 'slug'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostUpdateView, self).form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Delete a post by the author after authentication."""
    model = Post
    extra_context = {'title': 'Delete Post'}
    success_message = 'Post Deleted Successfully!'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False


class PostCategories(ListView):
    """List all posts' categories and filter posts by categories."""
    model = Post
    template_name = 'posts/posts_by_categories.html'
    paginate_by = 3

    def get_queryset(self):
        return Post.published.order_by('-date_posted')

    def get_context_data(self, *, object_list=None, **kwargs):
        category = None
        all_categories = Category.objects.order_by('name')
        posts = self.get_queryset()
        if self.kwargs.get('slug'):
            category = get_object_or_404(Category, slug=self.kwargs.get('slug'))
            posts = posts.filter(category=category)
        context = {
            'title': 'Categories',
            'category': category,
            'categories': all_categories,
        }
        return super(PostCategories, self).get_context_data(object_list=posts, **context)


class UserPostListView(ListView):
    """List all posts written by an author."""
    model = Post
    template_name = 'posts/user_posts.html'
    context_object_name = 'user_posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.published.all().filter(author=user)

    def get_context_data(self, *, object_list=None,  **kwargs):
        data = super(UserPostListView, self).get_context_data(object_list=self.get_queryset(), **kwargs)
        object_list = self.get_queryset()
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        # data = {
        #     # 'user_posts': self.get_queryset(),
        #     # 'user_posts': object_list,
        #     'title': f'{user.username} Posts',
        #     'user': user,
        # }
        data.update({
            'title': f'{user.username} Posts',
            'user': user,
            'user_posts': self.get_queryset(),
        })
        # return super(UserPostListView, self).get_context_data(object_list=self.get_queryset(), **data)
        return data


class ViewPostAuthorProfile(LoginRequiredMixin, DetailView):
    """View an author's profile."""
    model = User
    template_name = 'posts/user_profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        context = {
            'title': f'{user.username} Profile',
            'user': user
        }
        return context


class SearchView(FormView):
    """Search for posts."""
    template_name = 'posts/search.html'

    def get_context_data(self,  **kwargs):
        results = None
        if 'keyword' in self.request.GET:
            keyword = self.request.GET.get('keyword')
            search_vector = SearchVector('title', 'content')
            search_query = SearchQuery(keyword)
            results = Post.published.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)).filter(
                search=search_query).order_by('-rank')
        context = {
            'title': '{} Search Results'.format(self.request.GET['keyword']),
            'object_list': results,
            'values': self.request.GET
        }
        return context


class TrendingPostsView(ListView):
    """List some Trending posts."""
    model = Post
    template_name = 'posts/trending_posts.html'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        comments = Post.published.annotate(num_comments=Count('post_comments')).order_by('-num_comments')[:6]
        context = {
            'title': 'Trending Posts',
            'comments': comments,
        }
        return super(TrendingPostsView, self).get_context_data(object_list=comments, **context)

templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="font-weight-bolder">Delete {{ post.title }} &quest;</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <fieldset>
                    <h4>Do you want to delete this post &quot;{{ post.title }}&quot;?</h4>
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger font-weight-bolder">
                        Yes
                    </button>
                    <a href="{% url 'posts:post-detail' post.id post.slug post.date_posted.year post.date_posted.month post.date_posted.day %}" class="btn btn-success font-weight-bolder">
                        No
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load comments %}
{% load comments_xtd %}
{% load thumbnail %}
{% load timesince_filter %}

{% block content %}
    <div class="container">
        <div class="col mt-2">
            {% thumbnail post.author.profile.photo '50' as im %}
                <img src="{{ im.url }}" alt="{{ post.author.username }}" class="rounded-circle" width="50">
            {% endthumbnail %}
        </div>
        <div class="card">
            <div class="card-header">
                <a href="{% url 'posts:user-posts' post.author.username %}" class="card-link font-weight-bolder">
                    {{ post.author.username }}
                </a>&nbsp;
                <small class="text-secondary font-weight-bolder">
                    Posted: {{ post.date_posted|timesince|upto:',' }}&nbsp;ago
                </small>&nbsp;&nbsp;&nbsp;
                {% if post.updated.date > post.date_posted.date %}
                    <small class="text-secondary font-weight-bolder">
                        Updated: {{ post.updated|timesince|upto:',' }}&nbsp;ago
                    </small>
                {% endif %}
                <small class="text-secondary float-md-right font-weight-bolder">
                    {{ post.category }}
                </small>
            </div>
            <div class="card-body">
                <h5 class="text-center">
                    <a href="{% url 'posts:post-detail' post.pk post.slug post.date_posted.year post.date_posted.month post.date_posted.day %}" class="card-link">{{ post.title }}</a>
                </h5>
                <p>
                    {{ post.content|safe }}
                </p>
            </div>
            <div class="card-footer">
                {% for tag in post.tags.all %}
                    <a href="{% url 'posts:post_list_by_tag' tag.slug %}" class="text-decoration-none font-weight-bold text-secondary">
                        <i class="fas fa-tag"></i> {{ tag.name }} &nbsp;
                    </a>
                {% endfor %}
            </div>
        </div>
        {% if post.author_id == request.user.id %}
            <div class="container mt-3">
                <div class="row text-center">
                    <div class="col">
                        <a href="{% url 'posts:update-post' post.id post.slug %}" class="btn btn-success font-weight-bolder">
                            Update Post
                        </a>
                    </div>
                    <div class="col">
                        <a href="{% url 'posts:delete-post' post.id post.slug %}" class="btn btn-danger font-weight-bolder">
                            Delete Post
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
        {% get_comment_count for post as comment_count %}
        <div class="py-4 text-center">
            <a href="{% url 'posts:index' %}" class="text-decoration-none">
                <i class="fas fa-arrow-alt-circle-left"></i> Back to the post list
            </a> &nbsp;&sdot;&nbsp;
            {{ comment_count }} comment{{ comment_count|pluralize }} ha{{ comment_count|pluralize:"s,ve" }} been posted.
        </div>

        {% if comment_count %}
            <div class="container mt-4">
                <ul class="media-list">
                    {% render_xtdcomment_tree for post allow_flagging allow_feedback show_feedback %}
                </ul>
            </div>
        {% endif %}

        {% if post|can_receive_comments_from:user %}
            <div class="container col-md-8">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Post your comment
                    </div>
                    <div class="card-body">
                        {% render_comment_form for post %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="card mt-4 mb-5 text-center">
                <div class="card-body">
                    <p class="card-text font-weight-bold">
                        Only registered users can post comments. Please,
                        <a href="{% url 'users:login' %}?next={{ post.get_absolute_url }}" class="text-decoration-none card-link font-weight-bold">
                            Login <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header font-weight-bolder text-center">
                Create &sol; Update Post
            </div>
            <div class="card-body">
        <form action="" method="post" class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.media }}
            <button type="submit" class="btn btn-primary btn-block">
                Submit <i class="fas fa-paper-plane"></i>
            </button>
        </form>
                </div>
        </div>
    </div>
{% endblock %}

templates/posts/posts_by_categories.html
{% extends 'base.html' %}
{% load comments %}
{% load thumbnail %}
{% load timesince_filter %}

{% block content %}
    <!-- categories -->
    <div class="container">
        <div class="row">
            <div class="col-md-3 my-2">
                <div class="card-deck">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <p class="card-text font-weight-bolder">
                                <a href="{% url 'posts:categories' %}" class="card-link">
                                    All
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% for c in categories %}
                <div class="col-md-3 my-2">
                    <div class="card-deck">
                        <div class="card bg-light">
                            <div class="card-body text-center">
                                <p class="card-text font-weight-bolder">
                                    <a href="{{ c.get_absolute_url }}" class="card-link">
                                        {{ c.name }}
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="container mt-5 text-center">
                    <p class="lead font-weight-bolder">
                        No Categories Yet
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if category %}
        <div class="container mt-4">
            <h3 class="text-center mb-3 font-weight-bold">
                {{ category.name }} {{ category.categories.count }} post{{ category.categories.count|pluralize }}
            </h3>
            {% for post in object_list %}
                <div class="col mt-2">
                    {% thumbnail post.author.profile.photo '50' as im %}
                        <img src="{{ im.url }}" alt="{{ post.author.username }}" class="rounded-circle" width="50">
                    {% endthumbnail %}
                </div>
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'posts:user-posts' post.author.username %}" class="card-link font-weight-bolder">
                            {{ post.author.username }}
                        </a>&nbsp;
                        <small class="text-secondary font-weight-bolder">
                            Posted: {{ post.date_posted|timesince|upto:',' }}&nbsp;ago
                        </small>
                        {% if post.updated.date > post.date_posted.date %}
                            <small class="text-secondary font-weight-bolder">
                                Updated: {{ post.updated|timesince|upto:',' }}&nbsp;ago
                            </small>
                        {% endif %}
                        <small class="text-secondary float-md-right font-weight-bolder">
                            {{ post.category }}
                        </small>
                    </div>
                    <div class="card-body">
                        <h5 class="text-center">
{#                            <a href="{% url 'posts:post-detail' post.pk post.slug post.date_posted.year post.date_posted.month post.date_posted.day %}" class="card-link">{{ post.title }}</a>#}
                            <a href="{{ post.get_absolute_url }}" class="card-link">
                                {{ post.title }}
                            </a>
                        </h5>
                        <p>
                            {{ post.content|safe }}
                        </p>
                    </div>
                    <div class="card-footer">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'posts:post_list_by_tag' tag.slug %}" class="text-decoration-none font-weight-bold text-secondary">
                                <i class="fas fa-tag"></i> {{ tag.name }} &nbsp;
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <!-- comments -->
                <div class="container text-center my-2">
                    {% get_comment_count for post as comment_count %}
                    {% if comment_count %}
                        <p class="date">Published {{ post.publish }}
                            &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
                        </p>
                    {% else %}
                        <p>No Comments</p>
                    {% endif %}
                </div>
            {% empty %}
                 <div class="card">
                     <div class="card-header">
                         <h5 class="text-center font-weight-bolder">Post 404</h5>
                     </div>
                     <div class="card-body">
                         <h1 class="text-center">No post found</h1>
                     </div>
                 </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container mt-4">
            <h3 class="text-center mb-3 font-weight-bold">
                All {{ page_obj.paginator.count }} post{{ page_obj.paginator.count|pluralize }}
            </h3>
            {% for post in object_list %}
                <div class="col mt-2">
                    {% thumbnail post.author.profile.photo '50' as im %}
                        <img src="{{ im.url }}" alt="{{ post.author.username }}" class="rounded-circle" width="50">
                    {% endthumbnail %}
                </div>
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'posts:user-posts' post.author.username %}" class="card-link font-weight-bolder">
                            {{ post.author.username }}
                        </a>&nbsp;
                        <small class="text-secondary font-weight-bolder">
                            Posted: {{ post.date_posted|timesince|upto:',' }}&nbsp;ago
                        </small>
                        {% if post.updated.date > post.date_posted.date %}
                            <small class="text-secondary font-weight-bolder">
                                Updated: {{ post.updated|timesince|upto:',' }}&nbsp;ago
                            </small>
                        {% endif %}
                        <small class="text-secondary float-md-right font-weight-bolder">
                            {{ post.category }}
                        </small>
                    </div>
                    <div class="card-body">
                        <h5 class="text-center">
{#                            <a href="{% url 'posts:post-detail' post.pk post.slug post.date_posted.year post.date_posted.month post.date_posted.day %}" class="card-link">{{ post.title }}</a>#}
                            <a href="{{ post.get_absolute_url }}" class="card-link">
                                {{ post.title }}
                            </a>
                        </h5>
                        <p>
                            {{ post.content|safe }}
                        </p>
                    </div>
                    <div class="card-footer">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'posts:post_list_by_tag' tag.slug %}" class="text-decoration-none font-weight-bold text-secondary">
                                <i class="fas fa-tag"></i> {{ tag.name }} &nbsp;
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <!-- comments -->
                <div class="container text-center my-2">
                    {% get_comment_count for post as comment_count %}
                    {% if comment_count %}
                        <p class="date">Published {{ post.publish }}
                            &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
                        </p>
                    {% else %}
                        <p>No Comments</p>
                    {% endif %}
                </div>
            {% empty %}
                 <div class="card">
                     <div class="card-header">
                         <h5 class="text-center font-weight-bolder">Post 404</h5>
                     </div>
                     <div class="card-body">
                         <h1 class="text-center">No post found</h1>
                     </div>
                 </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/posts/user_posts.html
{% extends 'base.html' %}
{% load comments %}
{% load thumbnail %}
{% load timesince_filter %}

{% block content %}
    <div class="container">
        <h5>
            {{ user.username }} has written {{ user.author_post.count }} post{{ user.author_post.count|pluralize }} &verbar;
            <a href="{% url 'posts:view-author-profile' user.username %}" class="btn btn-outline-primary btn-sm font-weight-bolder">
                <i class="fas fa-eye"></i> View {{ user.username }} Profile
            </a>
        </h5>
    </div>
    <div class="container">
        {% for post in object_list %}
            <div class="col mt-2">
                {% thumbnail post.author.profile.photo '50' as im %}
                    <img src="{{ im.url }}" alt="{{ post.author.username }}" class="rounded-circle" width="50">
                {% endthumbnail %}
            </div>
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'posts:user-posts' post.author.username %}" class="card-link font-weight-bolder">
                        {{ post.author.username }}
                    </a>&nbsp;
                    <small class="text-secondary font-weight-bolder">
                        Posted: {{ post.date_posted|timesince|upto:',' }}&nbsp;ago
                    </small>
                    <small class="text-secondary float-md-right font-weight-bolder">
                        {{ post.category }}
                    </small>
                </div>
                <div class="card-body">
                    <h5 class="text-center">
                        <a href="{% url 'posts:post-detail' post.pk post.slug post.date_posted.year post.date_posted.month post.date_posted.day %}" class="card-link">{{ post.title }}</a>
                    </h5>
                    <p>
                        {{ post.content|safe }}
                    </p>
                </div>
                <div class="card-footer">
                    {% for tag in post.tags.all %}
                        <a href="{% url 'posts:post_list_by_tag' tag.slug %}" class="text-decoration-none font-weight-bold text-secondary">
                            <i class="fas fa-tag"></i> {{ tag.name }} &nbsp;
                        </a>
                    {% endfor %}
                </div>
            </div>
            <!-- comments -->
            <div class="container text-center my-2">
                {% get_comment_count for post as comment_count %}
                {% if comment_count %}
                    <p class="date">Published {{ post.publish }}
                        &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
                    </p>
                {% else %}
                    <p>No Comments</p>
                {% endif %}
            </div>
        {% empty %}
             <div class="card">
                 <div class="card-header">
                     <h5 class="text-center font-weight-bolder">Post 404</h5>
                 </div>
                 <div class="card-body">
                     <h1 class="text-center">No Post Yet</h1>
                 </div>
             </div>
        {% endfor %}
    </div>
{% endblock %}