blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('tech-blog-admin/', admin.site.urls),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *
from .feeds import LatestPostsFeed

app_name = 'posts'

urlpatterns = [
    path('post/<int:pk>/<slug:slugy>/<int:year>/<int:month>/<int:day>/', PostDetailView.as_view(), name='post-detail'),
    path('categories/<slug:slug>/', PostCategories.as_view(), name='post-by-categories'),
    path('profile/<slug:username>/', ViewPostAuthorProfile.as_view(), name='view-author-profile'),
    path('<str:username>/posts/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/<slug:slug>/update/', PostUpdateView.as_view(), name='update-post'),
    path('post/<int:pk>/<slug:slug>/delete/', PostDeleteView.as_view(), name='delete-post'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post_list_by_tag'),
    path('trending/', TrendingPostsView.as_view(), name='trending-posts'),
    path('feed/', LatestPostsFeed(), name='posts_feed'),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('categories/', PostCategories.as_view(), name='categories'),
    path('search', SearchView.as_view(), name='search'),
    path('', PostListView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    # authentication
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    # path('logout/', UserLogoutView.as_view(), name='logout'),

    # register and activate account
    path('register/', RegistrationView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm-email/<uidb64>/<token>/', ActivateAccountView.as_view(), name='confirm-email'),

    # change password
    path('password-change/', ChangePasswordView.as_view(), name='password-change'),
    path('password-change/done/', ChangePasswordDoneView.as_view(), name='password-change-done'),

    # reset password
    path('password-reset/', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset/done/', ResetPasswordDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset/complete/', ResetPasswordCompleteView.as_view(), name='password-reset-complete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils.text import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django_comments_xtd.models import XtdComment
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=70, unique=True)
    slug = models.SlugField(max_length=70, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('posts:post-by-categories', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.name}'


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    POST_STATUS = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True)
    author = models.ForeignKey(User, related_name='author_post', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='categories', on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=POST_STATUS, default='draft')
    content = HTMLField()
    date_posted = models.DateTimeField(default=now)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ('date_posted',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            count = 1
            if Post.objects.all().filter(slug=self.slug).exists():
                count += 1
                self.slug = slugify(self.title) + '-' + str(count)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk': self.pk, 'slugy': self.slug,
                                                    'year': self.date_posted.year,
                                                    'month': self.date_posted.month,
                                                    'day': self.date_posted.day})

    def __str__(self):
        return f'{self.title}'


class PostComment(XtdComment):
    post_comment = models.ForeignKey(Post, related_name='post_comments', on_delete=models.CASCADE)

templates/partials/_blog_extras.html
<!-- Blog Extras -->
<div>
    <div class="card">
        <div class="card-header">
            <h5 class="text-center font-weight-bolder">Extras</h5>
        </div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item text-center">
                    <a href="{% url 'posts:trending-posts' %}" class="text-decoration-none font-weight-bolder">
                        Trending Posts
                    </a>
                </li>
                <li class="list-group-item text-center">
                    <a href="#" class="text-decoration-none font-weight-bolder">
                        Notifications
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partials/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="container mt-3" id="alert-message">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags|title }}&colon;
                    {% endif %}
                </strong>
            {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top" id="home-navbar">
    <a href="{% url 'posts:index' %}" class="navbar-brand">
        <img src="{% static 'img/favicon.jpg' %}" alt="favicon" class="rounded-circle" width="30" height="30">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav grid-navbar">
            <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                <a href="{% url 'posts:index' %}" class="nav-link">
                    <i class="fas fa-home"></i> Home
                </a>
            </li>
            <li {% if 'categories' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                <a href="{% url 'posts:categories' %}" class="nav-link">
                    <i class="fas fa-newspaper"></i> Categories
                </a>
            </li>
            {% if request.user.is_authenticated and perms.posts.add_post %}
                <li {% if 'create-post' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                    <a href="{% url 'posts:create-post' %}" class="nav-link">
                        <i class="fas fa-plus-square"></i> Add Post
                    </a>
                </li>
            {% endif %}
            {% if request.user.is_authenticated and request.user.is_superuser %}
                <li class="nav-item mr-3">
                    <a href="/tech-blog-admin/" class="nav-link">
                        <i class="fas fa-user-shield"></i> Admin Panel
                    </a>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li {% if 'profile' in request.path %}class="nav-item active mr-3" {% else %}class="nav-item mr-3"{% endif %}>
                    <a href="{% url 'users:profile' %}" class="nav-link">
                        <img src="{{ request.user.profile.photo.url }}" alt="{{ request.user.username }}" class="rounded-circle" width="30" height="30">
                        &nbsp;{{ request.user.username }}&apos;s&nbsp; Profile
                    </a>
                </li>
                <li class="nav-item mr-3">
                    <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>
                    <form action="{% url 'users:logout' %}" id="logout" method="post">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                </li>
            {% else %}
                <li {% if 'register' in request.path %}class="nav-item active mr-3" {% else %}class="nav-item mr-3"{% endif %}>
                    <a href="{% url 'users:register' %}" class="nav-link">
                        Join
                    </a>
                </li>
                <li {% if 'login' in request.path %}class="nav-item active mr-3" {% else %}class="nav-item mr-3"{% endif %}>
                    <a href="{% url 'users:login' %}" class="nav-link">
                        Login
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/partials/_pagination.html
<div class="container text-center mt-5">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{ num }}" class="btn btn-info mb-4">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}" class="btn btn-outline-info mb-4">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}
    {% endif %}
</div>

templates/partials/_registration_side_note.html
<!-- sign up side note -->
<div class="card">
    <div class="card-header">
        <h5 class="text-center card-text font-weight-bolder">
            Join Today
        </h5>
    </div>
    <div class="card-body">
        <p class="font-italic card-text text-center">
            Join Tech Blog today to share your knowledge with millions of developers.
        </p>
        <p class="text-center card-text">
            <strong>
                <a href="{% url 'users:register' %}" class="text-decoration-none card-link">
                    Join Now <i class="fas fa-user-plus"></i>
                </a>
            </strong>
        </p>
    </div>
</div>

templates/partials/_search_form.html
<div class="container-fluid col-md-10">
    <form action="{% url 'posts:search' %}" method="get" class="form-group">
        <label for="search"></label>
        <div class="input-group">
            <input type="search" id="search" name="keyword" class="form-control form-control-lg" placeholder="Search for Posts..." value="{{ values.keyword }}">
            <div class="input-group-append">
                <button class="btn btn-success font-weight-bold">
                    <i class="fas fa-search fa-2x"></i>
                </button>
            </div>
        </div>
    </form>
</div>