blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('tech-blog-admin/', admin.site.urls),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    # authentication
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    # path('logout/', UserLogoutView.as_view(), name='logout'),

    # register and activate account
    path('register/', RegistrationView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm-email/<uidb64>/<token>/', ActivateAccountView.as_view(), name='confirm-email'),

    # change password
    path('password-change/', ChangePasswordView.as_view(), name='password-change'),
    path('password-change/done/', ChangePasswordDoneView.as_view(), name='password-change-done'),

    # reset password
    path('password-reset/', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset/done/', ResetPasswordDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset/complete/', ResetPasswordCompleteView.as_view(), name='password-reset-complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='users_photos/%Y/%m/%d/', default='avatar.png')
    facebook = models.URLField()
    twitter = models.URLField()
    linkedin = models.URLField()

    def __str__(self):
        return f'{self.user.username}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    """Form to register a new user."""
    username = forms.CharField(help_text='')
    email = forms.EmailField(label='Email', help_text='Provide your email')
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput, help_text='Password must be at least 8 characters long')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        cd_email = self.cleaned_data.get('email')
        if User.objects.filter(email=cd_email).exists():
            raise ValidationError('Email already exists.')
        return cd_email


class UserUpdateForm(forms.ModelForm):
    """Form to update a user's username and email."""
    email = forms.EmailField(max_length=200, widget=forms.EmailInput(attrs={'class': 'emailinput form-control mb-1'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    """Form to update a user's image and social network links."""
    # photo = forms.ImageField(label='Choose file',
    #                          widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}))
    photo = forms.ImageField(label='Photo',
                             widget=forms.ClearableFileInput(attrs={'class': 'border'}))
    facebook = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control mb-1'}),
                              help_text='https://facebook.com/username/')
    twitter = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control mb-1'}),
                             help_text='https://twitter.com/username/')
    linkedin = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control mb-1'}),
                              help_text='https://linkedin.com/in/username/')

    class Meta:
        model = Profile
        fields = ['photo', 'facebook', 'twitter', 'linkedin']

    def clean_facebook(self):
        cd_facebook_url = self.cleaned_data.get('facebook')
        if len('https://facebook.com/') == len(cd_facebook_url) or len(cd_facebook_url) < len('https://facebook.com/'):
            raise ValidationError('Invalid Facebook username')
        return cd_facebook_url

    def clean_twitter(self):
        cd_twitter_url = self.cleaned_data.get('twitter')
        if len('https://twitter.com/') == len(cd_twitter_url) or len(cd_twitter_url) < len('https://twitter.com/'):
            raise ValidationError('Invalid Twitter username')
        return cd_twitter_url

    def clean_linkedin(self):
        cd_linkedin_url = self.cleaned_data.get('linkedin')
        if len('https://linkedin.com/') == len(cd_linkedin_url) or len(cd_linkedin_url) < len('https://linkedin.com/'):
            raise ValidationError('Invalid Linkedin username')
        return cd_linkedin_url

users/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, View
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string, get_template
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm


UserModel = get_user_model()


class RegistrationView(SuccessMessageMixin, View):
    """Register a new user."""
    success_message = '%(user)s Your Account Has Successfully Created!'

    def get(self, request):
        context = {
            'title': 'Register',
            'form': UserRegistrationForm()
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate Your Account.'
            activation_context = {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user)
            }
            # msg = render_to_string('users/activate_account.html', activation_context)
            msg = get_template('users/activate_account.html').render(activation_context)
            to_email = user.email
            send_email = EmailMessage(mail_subject, msg, to=[to_email])
            send_email.content_subtype = 'html'
            send_email.send()
            messages.info(request, 'Please Confirm Your Email Address.')
            return redirect('posts:index')
        context = {
            'title': 'Register',
            'form': form
        }
        return render(request, 'users/register.html', context)


class ActivateAccountView(TemplateView, View):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(self.kwargs.get('uidb64')).decode()
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and default_token_generator.check_token(user, self.kwargs.get('token')):
            user.is_active = True
            user.save()
            messages.success(request, 'Account Activated Successfully. You Can Now Login')
            return redirect('users:login')
        else:
            messages.error(request, 'Invalid Activation Link')
            return redirect('users:register')


class ProfileView(LoginRequiredMixin, TemplateView, View):
    """User's Profile"""
    template_name = 'users/profile.html'
    default_data = {
        'facebook': 'https://facebook.com/',
        'twitter': 'https://twitter.com/',
        'linkedin': 'https://linkedin.com/'
    }

    def get_user_formset(self, data=None):
        return UserUpdateForm(instance=self.request.user, data=data)

    def get_profile_formset(self, data=None, files=None):
        profile_formset = ProfileUpdateForm(instance=self.request.user.profile, data=data, files=files)
        # profile_formset['photo'].label_tag(attrs={'class': 'custom-file-label'})
        return profile_formset

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
            'user_form': self.get_user_formset(),
            'profile_form': self.get_profile_formset(),
            'title': 'Profile'
        })

    def post(self, request, *args, **kwargs):
        user_formset = self.get_user_formset(data=request.POST)
        profile_formset = self.get_profile_formset(data=request.POST, files=request.FILES)

        if user_formset.is_valid() and profile_formset.is_valid():
            user_formset.save()
            profile_formset.save()
            messages.success(request, 'Your Account is Updated!!!')
            return HttpResponseRedirect('/profile/')
        return self.render_to_response({
            'user_form': user_formset,
            'profile_form': profile_formset,
            'title': 'Profile'
        })


class UserLoginView(SuccessMessageMixin, auth_views.LoginView):
    """User login view"""
    extra_context = {'title': 'Login'}
    template_name = 'users/login.html'
    success_message = 'Login Successful'


def logout_view(request):
    """User logout view"""
    logout(request)
    messages.success(request, 'Logged Out')
    return redirect('posts:index')


class UserLogoutView(SuccessMessageMixin, auth_views.LogoutView):
    """User logout view"""
    success_message = 'Logged Out'

    def post(self, request, *args, **kwargs):
        messages.success(request, 'Logged Out')
        return super(UserLogoutView, self).post(request, *args, **kwargs)


class ChangePasswordView(auth_views.PasswordChangeView):
    template_name = 'users/passwords/password_change.html'
    extra_context = {'title': 'Password Change'}
    success_url = '/password-change/done/'


class ChangePasswordDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'users/passwords/password_change_done.html'
    extra_context = {'title': 'Password Changed Done'}


class ResetPasswordView(auth_views.PasswordResetView):
    template_name = 'users/passwords/password_reset.html'
    extra_context = {'title': 'Password Reset'}
    success_url = reverse_lazy('users:password-reset-done')
    email_template_name = 'users/passwords/password_reset_email.html'


class ResetPasswordDoneView(auth_views.PasswordResetDoneView):
    template_name = 'users/passwords/password_reset_done.html'
    extra_context = {'title': 'Password Reset Done'}


class ResetPasswordConfirmView(auth_views.PasswordResetConfirmView):
    extra_context = {'title': 'Confirm Password Reset'}
    success_url = reverse_lazy('users:password-reset-complete')
    template_name = 'users/passwords/password_reset_confirm.html'


class ResetPasswordCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'users/passwords/password_reset_complete.html'
    extra_context = {'title': 'Password Reset Complete'}

templates/users/activate_account.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,

    <a href="http://{{ domain }}{% url 'users:confirm-email' uidb64=uid token=token %}">
        Verify Email
    </a>

    If you think, it's not you, then just ignore this email.
{% endautoescape %}

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container col-lg-8 mt-4">
        <div class="card">
            <div class="card-header text-center font-weight-bolder">
                Login
            </div>
            <div class="card-body">
                <form method="post" class="form-group">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary form-control font-weight-bolder">
                        Login <i class="fas fa-sign-in-alt"></i>
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <small class="font-weight-bolder">
                    Don't have an account &quest; &nbsp;
                    <a href="{% url 'users:register' %}" class="card-link">
                        Sign Up
                    </a>
                </small>&verbar;
                <small class="font-weight-bolder">
                    <a href="{% url 'users:password-reset' %}" class="card-link">
                        Forgot Password
                    </a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h5 class="font-weight-bolder">Your Profile</h5>
            </div>
            <div class="card-body">
                {% thumbnail user.profile.photo '300x300' as im %}
                    <img src="{{ im.url }}" alt="{{ user.username }}&apos;s photo" class="img-thumbnail" width="{{ im.width }}">
                {% endthumbnail %}
                <form action="{% url 'users:profile' %}" method="post" class="form-group mt-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                    <button type="submit" class="btn btn-success form-control font-weight-bolder">
                        Update Changes
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <small>
                    <a href="{% url 'users:password-change' %}" class="btn btn-sm btn-primary font-weight-bolder card-link">
                        Change Password <i class="fas fa-lock"></i>
                    </a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container-fluid col-lg-8 mt-4">
        <div class="card">
            <div class="card-header card-text font-weight-bolder">
                Sign Up Form <i class="fas fa-user-plus"></i>
            </div>
            <div class="card-body">
                <form action="{% url 'users:register' %}" method="post" class="form-group">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="form-control btn btn-primary">
                        Submit
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <small class="font-weight-bolder">
                    Already have an account ? &nbsp;
                    <a href="{% url 'users:login' %}" class="card-link">
                        Login <i class="fas fa-sign-in-alt"></i>
                    </a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}